### ISSUE TITLE
pyrecordio is not compatible with tensorflow v1.13.0 and above.

### ISSUE THREAD

**Issue by yuyicg** [elasticdl/pyrecordio#21]
test case tf_recordio_dataset_test.py failed with error message below: 
```
Traceback (most recent call last):
  File "tf_recordio_dataset.py", line 34, in <module>
    recordio = tf.load_op_library(install_dir + '/recordio/tensorflow_op/python/librecordio_dataset_op.so')
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/load_library.py", line 64, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /usr/local/lib/python3.5/dist-packages/recordio/tensorflow_op/python/librecordio_dataset_op.so: undefined symbol: _ZTVN10tensorflow4data11DatasetBaseE
```

**Comment by skydoorkai** [comment]
bazel build result does not work. 
Used Makefile according to https://github.com/tensorflow/custom-op/blob/master/Makefile
the resulting whl works:

my hack Makefile:
```
CXX := g++
NVCC := nvcc
PYTHON_BIN_PATH = python

ZERO_OUT_SRCS = $(wildcard recordio/tensorflow_op/cc/*.cc)

TF_CFLAGS := $(shell $(PYTHON_BIN_PATH) -c 'import tensorflow as tf; print(" ".join(tf.sysconfig.get_compile_flags()))')
TF_LFLAGS := $(shell $(PYTHON_BIN_PATH) -c 'import tensorflow as tf; print(" ".join(tf.sysconfig.get_link_flags()))')

CFLAGS = ${TF_CFLAGS} -fPIC -O2 -std=c++11
LDFLAGS = -shared ${TF_LFLAGS}

ZERO_OUT_TARGET_LIB = recordio/tensorflow_op/python/librecordio_dataset_op.so

zero_out_op: $(ZERO_OUT_TARGET_LIB)

$(ZERO_OUT_TARGET_LIB): $(ZERO_OUT_SRCS)
        $(CXX) $(CFLAGS) -o $@ $^ ${LDFLAGS}

zero_out_pip_pkg: $(ZERO_OUT_TARGET_LIB)
        ./build_pip_pkg.sh make artifacts


clean:
        rm -f $(ZERO_OUT_TARGET_LIB)
```
